// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Marain.Claims.Specs.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ClaimPermissionsStore")]
    [NUnit.Framework.CategoryAttribute("useTransientTenant")]
    [NUnit.Framework.CategoryAttribute("perFeatureContainer")]
    public partial class ClaimPermissionsStoreFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "useTransientTenant",
                "perFeatureContainer"};
        
#line 1 "ClaimPermissionsStore.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "ClaimPermissionsStore", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "AccessType",
                        "Resource",
                        "Permission"});
            table2.AddRow(new string[] {
                        "GET",
                        "marain/test/resource1",
                        "Allow"});
#line 7
 testRunner.Given("I have a list of resource access rules called \"rules-1\"", ((string)(null)), table2, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "AccessType",
                        "Resource",
                        "Permission"});
            table3.AddRow(new string[] {
                        "GET",
                        "marain/test/resource2",
                        "Allow"});
#line 10
 testRunner.Given("I have a list of resource access rules called \"rules-2\"", ((string)(null)), table3, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "DisplayName",
                        "Rules"});
            table4.AddRow(new string[] {
                        "rulesets-1",
                        "Ruleset 1",
                        "{rules-1}"});
            table4.AddRow(new string[] {
                        "rulesets-2",
                        "Ruleset 2",
                        "{rules-2}"});
#line 13
 testRunner.And("I have resource access rulesets called \"rulesets\"", ((string)(null)), table4, "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "DisplayName",
                        "Rules"});
            table5.AddRow(new string[] {
                        "rulesets-1",
                        "Ruleset 1",
                        "{rules-1}"});
#line 17
 testRunner.And("I have resource access rulesets called \"rulesets-single\"", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "ResourceAccessRules",
                        "ResourceAccessRulesets"});
            table6.AddRow(new string[] {
                        "claimpermissions-1",
                        "",
                        "{rulesets}"});
            table6.AddRow(new string[] {
                        "claimpermissions-2",
                        "",
                        "{rulesets-single}"});
#line 20
 testRunner.And("I have claim permissions called \"claimpermissions\"", ((string)(null)), table6, "And ");
#line hidden
#line 24
 testRunner.And("I have saved the resource access rulesets called \"rulesets\" to the resource acces" +
                    "s ruleset store", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 25
 testRunner.And("I have created the claim permissions called \"claimpermissions\" in the claim permi" +
                    "ssions store", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieving claim permissions from the repository")]
        [NUnit.Framework.CategoryAttribute("useChildObjects")]
        public void RetrievingClaimPermissionsFromTheRepository()
        {
            string[] tagsOfScenario = new string[] {
                    "useChildObjects"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieving claim permissions from the repository", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 29
 testRunner.When("I request the claim permission with Id \"claimpermissions-1\" from the claim permis" +
                        "sions store", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 30
 testRunner.Then("the claim permission is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 31
 testRunner.And("the resource access rulesets on the claim permission match the rulesets \"rulesets" +
                        "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieving a batch of claim permissions from the repository")]
        [NUnit.Framework.CategoryAttribute("useChildObjects")]
        public void RetrievingABatchOfClaimPermissionsFromTheRepository()
        {
            string[] tagsOfScenario = new string[] {
                    "useChildObjects"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieving a batch of claim permissions from the repository", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "ClaimPermissionsId"});
                table7.AddRow(new string[] {
                            "claimpermissions-1"});
                table7.AddRow(new string[] {
                            "claimpermissions-2"});
#line 35
 testRunner.When("I request a batch of claim permissions by Id from the claim permissions store", ((string)(null)), table7, "When ");
#line hidden
#line 39
 testRunner.Then("the claim permissions are returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "ClaimPermissionsId",
                            "ExpectedRulesets"});
                table8.AddRow(new string[] {
                            "claimpermissions-1",
                            "rulesets"});
                table8.AddRow(new string[] {
                            "claimpermissions-2",
                            "rulesets-single"});
#line 40
 testRunner.And("the resource access rulesets on the claim permissions match the expected rulesets" +
                        "", ((string)(null)), table8, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieving a batch of claim permissions from the repository with duplicate claim " +
            "permission Ids automatically deduplicates the requests")]
        [NUnit.Framework.CategoryAttribute("useChildObjects")]
        public void RetrievingABatchOfClaimPermissionsFromTheRepositoryWithDuplicateClaimPermissionIdsAutomaticallyDeduplicatesTheRequests()
        {
            string[] tagsOfScenario = new string[] {
                    "useChildObjects"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieving a batch of claim permissions from the repository with duplicate claim " +
                    "permission Ids automatically deduplicates the requests", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 46
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "ClaimPermissionsId"});
                table9.AddRow(new string[] {
                            "claimpermissions-1"});
                table9.AddRow(new string[] {
                            "claimpermissions-1"});
#line 47
 testRunner.When("I request a batch of claim permissions by Id from the claim permissions store", ((string)(null)), table9, "When ");
#line hidden
#line 51
 testRunner.Then("the claim permissions are returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "ClaimPermissionsId",
                            "ExpectedRulesets"});
                table10.AddRow(new string[] {
                            "claimpermissions-1",
                            "rulesets"});
#line 52
 testRunner.And("the resource access rulesets on the claim permissions match the expected rulesets" +
                        "", ((string)(null)), table10, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieving claim permissions with an invalid Id")]
        [NUnit.Framework.CategoryAttribute("useChildObjects")]
        public void RetrievingClaimPermissionsWithAnInvalidId()
        {
            string[] tagsOfScenario = new string[] {
                    "useChildObjects"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieving claim permissions with an invalid Id", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 57
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 58
 testRunner.And("an id exists named \"incorrectid\" but there is no claims permission associated wit" +
                        "h it", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 59
 testRunner.When("I request the claim permission with Id \"incorrectid\" from the claim permissions s" +
                        "tore", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 60
 testRunner.Then("a \"ClaimPermissionsNotFoundException\" exception is thrown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieving claim permissions when one or more of the referenced rule sets are mis" +
            "sing")]
        [NUnit.Framework.CategoryAttribute("useChildObjects")]
        public void RetrievingClaimPermissionsWhenOneOrMoreOfTheReferencedRuleSetsAreMissing()
        {
            string[] tagsOfScenario = new string[] {
                    "useChildObjects"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieving claim permissions when one or more of the referenced rule sets are mis" +
                    "sing", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 63
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "DisplayName",
                            "Rules"});
                table11.AddRow(new string[] {
                            "rulesets-3",
                            "Ruleset 3",
                            "{rules-1}"});
                table11.AddRow(new string[] {
                            "rulesets-4",
                            "Ruleset 4",
                            "{rules-2}"});
#line 64
 testRunner.Given("I have resource access rulesets called \"rulesets-unsaved\"", ((string)(null)), table11, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "ResourceAccessRules",
                            "ResourceAccessRulesets"});
                table12.AddRow(new string[] {
                            "claimpermissions-2",
                            "",
                            "{rulesets-unsaved}"});
#line 68
 testRunner.And("I have claim permissions called \"claimpermissions-2\"", ((string)(null)), table12, "And ");
#line hidden
#line 71
 testRunner.And("I have created the claim permissions called \"claimpermissions-2\" in the claim per" +
                        "missions store", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 72
 testRunner.When("I request the claim permission with Id \"claimpermissions-2\" from the claim permis" +
                        "sions store", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 73
 testRunner.Then("a \"ResourceAccessRuleSetNotFoundException\" exception is thrown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
