trigger:
  branches:
    include:
    - master
    - feature/*
  tags:
    include:
    - '*'

resources:
  repositories:
    - repository: recommended_practices
      type: github
      name: endjin/Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub
      endpoint: marain-github

jobs:
- template: templates/build.and.release.yml@recommended_practices
  parameters:
    vmImage: 'ubuntu-latest'
    service_connection_nuget_org: $(Endjin_Service_Connection_NuGet_Org)
    service_connection_github: $(Endjin_Service_Connection_GitHub)
    solution_to_build: $(Endjin_Solution_To_Build)
    postCustomEnvironmentVariables:
      - powershell: |
          Write-Host "##vso[task.setvariable variable=TestBlobStorageConfiguration__AccountName]$Env:ENDJIN_BLOBSTORAGEACCOUNTNAME"
          Write-Host "##vso[task.setvariable variable=TestBlobStorageConfiguration__AccountKeySecretName]$Env:ENDJIN_BLOBSTORAGEACCOUNTKEYSECRETNAME"
          Write-Host "##vso[task.setvariable variable=TestBlobStorageConfiguration__KeyVaultName]$Env:ENDJIN_BLOBSTORAGEKEYVAULTNAME"
          Write-Host "##vso[task.setvariable variable=AzureServicesAuthConnectionString]$Env:ENDJIN_AZURESERVICESAUTHCONNECTIONSTRING"
        displayName: 'Set Azure Connection String Environment Variable'
        env:
          ENDJIN_BLOBSTORAGEACCOUNTNAME: $(Endjin_BlobStorageAccountName)
          ENDJIN_BLOBSTORAGEACCOUNTKEYSECRETNAME: $(Endjin_BlobStorageAccountKeySecretName)
          ENDJIN_BLOBSTORAGEKEYVAULTNAME: $(Endjin_BlobStorageKeyVaultName)
          ENDJIN_AZURESERVICESAUTHCONNECTIONSTRING: $(Endjin_AzureServicesAuthConnectionString)
    postSpecs:
    - task: ArchiveFiles@2
      displayName: 'Archive Function App'
      inputs:
        rootFolderOrFile: 'Solutions/Marain.Claims.Host.Functions/bin/Release/netcoreapp3.1/'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/Release/Marain.Claims.Host.Functions.zip'
        replaceExistingArchive: true
    - task: ArchiveFiles@2
      displayName: 'Archive Deployment Artifacts'
      inputs:
        rootFolderOrFile: 'Solutions/Marain.Claims.Deployment'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/Release/Marain.Claims.Deployment.zip'
        replaceExistingArchive: true
    netSdkVersion: '3.x'