// <copyright file="GlobalSuppressions.cs" company="Endjin Limited">
// Copyright (c) Endjin Limited. All rights reserved.
// </copyright>

// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0051:Remove unused private members", Justification = "Required by CommandLineApplication framework.", Scope = "member", Target = "~M:Marain.Claims.SetupTool.Commands.BootstrapClaimsTenant.OnExecuteAsync(McMaster.Extensions.CommandLineUtils.CommandLineApplication,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Required by CommandLineApplication framework.", Scope = "member", Target = "~M:Marain.Claims.SetupTool.Commands.BootstrapClaimsTenant.OnExecuteAsync(McMaster.Extensions.CommandLineUtils.CommandLineApplication,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Required by CommandLineApplication framework.", Scope = "member", Target = "~M:Marain.Claims.SetupTool.Commands.ClaimsSetup.OnExecuteAsync(McMaster.Extensions.CommandLineUtils.CommandLineApplication,McMaster.Extensions.CommandLineUtils.IConsole)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0051:Remove unused private members", Justification = "Required by CommandLineApplication framework.", Scope = "member", Target = "~M:Marain.Claims.SetupTool.Commands.ClaimsSetup.OnExecuteAsync(McMaster.Extensions.CommandLineUtils.CommandLineApplication,McMaster.Extensions.CommandLineUtils.IConsole)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0051:Remove unused private members", Justification = "Required by CommandLineApplication framework.", Scope = "member", Target = "~M:Marain.Claims.SetupTool.Commands.DefineRulesetsAndClaimPermissions.OnExecuteAsync(McMaster.Extensions.CommandLineUtils.CommandLineApplication,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Required by CommandLineApplication framework.", Scope = "member", Target = "~M:Marain.Claims.SetupTool.Commands.DefineRulesetsAndClaimPermissions.OnExecuteAsync(McMaster.Extensions.CommandLineUtils.CommandLineApplication,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0051:Remove unused private members", Justification = "Required by CommandLineApplication framework.", Scope = "member", Target = "~M:Marain.Claims.SetupTool.Commands.ShowAppIdentityInformation.OnExecuteAsync(McMaster.Extensions.CommandLineUtils.CommandLineApplication,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Required by CommandLineApplication framework.", Scope = "member", Target = "~M:Marain.Claims.SetupTool.Commands.ShowAppIdentityInformation.OnExecuteAsync(McMaster.Extensions.CommandLineUtils.CommandLineApplication,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Int32}")]