// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Marain.Claims.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClaimPermissionsBatchResponseItem : ClaimPermissionsBatchRequestItem
    {
        /// <summary>
        /// Initializes a new instance of the ClaimPermissionsBatchResponseItem
        /// class.
        /// </summary>
        public ClaimPermissionsBatchResponseItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClaimPermissionsBatchResponseItem
        /// class.
        /// </summary>
        /// <param name="permission">Possible values include: 'allow',
        /// 'deny'</param>
        public ClaimPermissionsBatchResponseItem(string claimPermissionsId = default(string), string resourceUri = default(string), string resourceAccessType = default(string), int? responseCode = default(int?), string permission = default(string))
            : base(claimPermissionsId, resourceUri, resourceAccessType)
        {
            ResponseCode = responseCode;
            Permission = permission;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "responseCode")]
        public int? ResponseCode { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'allow', 'deny'
        /// </summary>
        [JsonProperty(PropertyName = "permission")]
        public string Permission { get; set; }

    }
}
