// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Marain.Claims.Client.Models
{
    using System.Linq;

    public partial class ClaimPermissionsBatchRequestItemWithPostExample : ClaimPermissionsBatchRequestItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ClaimPermissionsBatchRequestItemWithPostExample class.
        /// </summary>
        public ClaimPermissionsBatchRequestItemWithPostExample()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// ClaimPermissionsBatchRequestItemWithPostExample class.
        /// </summary>
        public ClaimPermissionsBatchRequestItemWithPostExample(string claimPermissionsId = default(string), string resourceUri = default(string), string resourceAccessType = default(string))
            : base(claimPermissionsId, resourceUri, resourceAccessType)
        {
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

    }
}
