// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Marain.Claims.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClaimPermissionsBatchRequestItem
    {
        /// <summary>
        /// Initializes a new instance of the ClaimPermissionsBatchRequestItem
        /// class.
        /// </summary>
        public ClaimPermissionsBatchRequestItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClaimPermissionsBatchRequestItem
        /// class.
        /// </summary>
        public ClaimPermissionsBatchRequestItem(string claimPermissionsId = default(string), string resourceUri = default(string), string resourceAccessType = default(string))
        {
            ClaimPermissionsId = claimPermissionsId;
            ResourceUri = resourceUri;
            ResourceAccessType = resourceAccessType;
            CustomInit();
        }
        /// <summary>
        /// Static constructor for ClaimPermissionsBatchRequestItem class.
        /// </summary>
        static ClaimPermissionsBatchRequestItem()
        {
            ContentType = "application/vnd.marain.claims.claimpermissionsbatchrequestitem";
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "claimPermissionsId")]
        public string ClaimPermissionsId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resourceUri")]
        public string ResourceUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resourceAccessType")]
        public string ResourceAccessType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contentType")]
        public static string ContentType { get; private set; }

    }
}
