// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Marain.Claims.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PermissionResult
    {
        /// <summary>
        /// Initializes a new instance of the PermissionResult class.
        /// </summary>
        public PermissionResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PermissionResult class.
        /// </summary>
        /// <param name="permission">Possible values include: 'allow',
        /// 'deny'</param>
        public PermissionResult(string permission = default(string))
        {
            Permission = permission;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'allow', 'deny'
        /// </summary>
        [JsonProperty(PropertyName = "permission")]
        public string Permission { get; set; }

    }
}
