// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Marain.Claims.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ResourceAccessRuleSetIdOnly
    {
        /// <summary>
        /// Initializes a new instance of the ResourceAccessRuleSetIdOnly
        /// class.
        /// </summary>
        public ResourceAccessRuleSetIdOnly()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ResourceAccessRuleSetIdOnly
        /// class.
        /// </summary>
        public ResourceAccessRuleSetIdOnly(string id)
        {
            Id = id;
            CustomInit();
        }
        /// <summary>
        /// Static constructor for ResourceAccessRuleSetIdOnly class.
        /// </summary>
        static ResourceAccessRuleSetIdOnly()
        {
            ContentType = "application/vnd.marain.claims.resourceaccessruleset";
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contentType")]
        public static string ContentType { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Id == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Id");
            }
        }
    }
}
