// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Marain.Claims.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ResourceAccessRuleSet
    {
        /// <summary>
        /// Initializes a new instance of the ResourceAccessRuleSet class.
        /// </summary>
        public ResourceAccessRuleSet()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ResourceAccessRuleSet class.
        /// </summary>
        public ResourceAccessRuleSet(string id, string eTag = default(string), string displayName = default(string), IList<ResourceAccessRule> rules = default(IList<ResourceAccessRule>))
        {
            Id = id;
            ETag = eTag;
            DisplayName = displayName;
            Rules = rules;
            CustomInit();
        }
        /// <summary>
        /// Static constructor for ResourceAccessRuleSet class.
        /// </summary>
        static ResourceAccessRuleSet()
        {
            ContentType = "application/vnd.marain.claims.resourceaccessruleset";
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eTag")]
        public string ETag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rules")]
        public IList<ResourceAccessRule> Rules { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contentType")]
        public static string ContentType { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Id == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Id");
            }
            if (Rules != null)
            {
                foreach (var element in Rules)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
